# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Dependency manager for Cocoa projects
brew "cocoapods"
# GNU File, Shell, and Text utilities
brew "coreutils"
# GNU debugger
brew "gdb"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"
# Configurable static site generator
brew "hugo"
# Generic machine emulator and virtualizer
brew "qemu"
# Additional guest agents for Lima
brew "lima-additional-guestagents"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Manage multiple Node.js versions
brew "nvm"
# Development kit for the Java programming language
brew "openjdk@21"
# OpenShift command-line interface tools
brew "openshift-cli"
# SSL/TLS VPN implementing OSI layer 2 or 3 secure network extension
brew "openvpn"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Python version management
brew "pyenv"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Tools for and transforming and inspecting PDF files
brew "qpdf"
# Utility that provides fast incremental file transfer
brew "rsync"
# Experimental Rust compiler front-end for IDEs
brew "rust-analyzer"
# Rust toolchain installer
brew "rustup"
# Non-interactive SSH password auth
brew "sshpass"
# User interface to the TELNET protocol
brew "telnet"
# Internet file retriever
brew "wget"
# Cross-platform C++ GUI toolkit
brew "wxwidgets"
# Modular BSD reimplementation of NASM
brew "yasm"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Android SDK component
cask "android-platform-tools"
# Kext-less implementation of FUSE
cask "fuse-t"
# File system integration
cask "macfuse"
# Integrated packaging environment
cask "packages"
cargo "cbindgen"
npm "@google/gemini-cli"
npm "corepack"
npm "yarn"
